services:
  telegram-webhook:
    build: .
    container_name: telegram-webhook
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - ngrok
    restart: unless-stopped
    command: ["./start.sh"]

  ngrok:
    image: ngrok/ngrok:alpine
    container_name: ngrok
    ports:
      - 4040:4040
    env_file:
      - .env
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    restart: unless-stopped
    command:
      - "http"
      - "http://telegram-webhook:8000"
    healthcheck:
      test: >
        wget -qO- http://localhost:4040/api/tunnels | grep -q '"public_url"'
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 3s
